### ISSUE TITLE
Clarify license in readme

### ISSUE THREAD

**Issue by dfyx** [carlosbaraza/web-assembly-logo#1]
There isn't one "Creative Commons" license. CC is a collection of several licenses with different terms. Please specify which one you mean. It looks like the one in your `LICENSE` file is [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) which isn't a very good fit for a logo because it means that every use of the logo must contain a link back to this repository. For logos that are meant to be used on tons of websites as well as physical articles such as t-shirts, cups, stickers, etc., [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or the roughly equivalent [WTFPL](http://www.wtfpl.net/about/) are a better fit. Both essentially mean "do whatever you want".

**Comment by carlosbaraza** [comment]
Hi Christian,

I changed it.

Thanks for the information!

I should spend some time understanding the different licenses, but I keep
procrastinating it.

Cheers,
Carlos
