### ISSUE TITLE
Possible font rendering issues in dist svg

### ISSUE THREAD

**Issue by topokel** [carlosbaraza/web-assembly-logo#2]
The dist svg's lettering isn't rendered as `<path>`'s so if the user doesn't have the correct font or bad font rendering the logo could get garbled. Illustrator svg exports keep impressing me though, I remember they used to be bulky with lots of useless markup and [this is about as lean as it gets!](https://raw.githubusercontent.com/carlosbaraza/web-assembly-logo/master/dist/logo/web-assembly-logo-white.svg)

**Comment by carlosbaraza** [comment]
You are right. We should probably vectorize the text.

**Comment by carlosbaraza** [comment]
Fixed
