### ISSUE TITLE
Change WA to WASM?

### ISSUE THREAD

**Issue by titzer** [carlosbaraza/web-assembly-logo#4]
(Couldn't find a way to open an issue on the fork on the WebAssembly repo).

Some people have expressed a preference for the "WA" in the puzzle piece to be "WASM".

Thoughts?

**Comment by carlosbaraza** [comment]
This was discussed in the issues: https://github.com/WebAssembly/design/issues/980#issuecomment-278503786 and https://github.com/WebAssembly/design/issues/112.

It is not straight forward to fit this design with `wasm`, as it would break with the two letter similitude with JS logo. However, I am happy to keep this open and I will try exploring some alternatives with `wasm`.

**Comment by carlosbaraza** [comment]
At this point, the WA version is pretty widespread, so this change will most likely never happen. I close the issue.
